SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT I.ANIMAL_ID,  DATEDIFF(O.DATETIME, I.DATETIME) AS TIME, I.NAME
        FROM ANIMAL_INS I
        INNER JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
        ORDER BY TIME DESC
        LIMIT 2) A
